apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ template "laravel-rocket.name" . }}-{{ .Release.Time.Seconds }}-env
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "laravel-rocket.name" . }}
    chart: {{ template "laravel-rocket.chart" . }} 
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  .env: |-
{{ .Files.Get .Values.app.envFilePath | b64enc | indent 4 }}