version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: laravel-rocket-helm-chart
          environment:
            - GITHUB_PAGES_REPO: tuantranf/laravel-rocket-helm-chart
          command: wget -O - https://raw.githubusercontent.com/tuantranf/helm-github-pages/master/publish.sh | sh