apiVersion: v1
kind: Service
metadata:
  name: {{ template "podder-task-bean.fullname" . }}
  labels:
    app: {{ template "podder-task-bean.name" . }}
    chart: {{ template "podder-task-bean.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ template "podder-task-bean.name" . }}
    release: {{ .Release.Name }}
