apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  name: {{ template "laravel.fullname" . }}-{{ .Release.Time.Seconds }}-apache
  labels:
    app: {{ template "laravel.name" . }}
    chart: {{ template "laravel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  vhost.conf: |-
{{ .Files.Get "vhost.conf" | indent 4 }}
